[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mantle_testnet = "https://rpc.testnet.mantle.xyz"

[etherscan]
mantle_testnet = { key = "${MANTLESCAN_API_KEY}", url = "https://api-testnet.mantlescan.info/api" }
